name: it-service

services:
  frontend:
    container_name: it-service-frontend
    build:
      context: .\packages\frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - type: bind
        source: .\packages\frontend
        target: /app
      - type: volume
        source: frontend-node-modules
        target: /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - bot
    networks:
      - it-service-network

  bot:
    container_name: it-service-bot
    build:
      context: .\packages\discord-bot
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: .\packages\discord-bot
        target: /app
      - type: volume
        source: bot-node-modules
        target: /app/node_modules
      - type: volume
        source: bot-uploads
        target: /app/uploads
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - it-service-network

networks:
  it-service-network:
    driver: bridge

volumes:
  frontend-node-modules:
  bot-node-modules:
  bot-uploads: 