version: '3.8'

services:
  frontend:
    container_name: it-service-frontend
    build:
      context: ./packages/static-frontend  # Correct path
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - frontend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - bot
    networks:
      - it-service-network
    restart: unless-stopped

  bot:
    container_name: it-service-bot
    build:
      context: ./packages/discord-bot
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - bot-node-modules:/app/node_modules
      - bot-uploads:/app/uploads
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - it-service-network
    restart: unless-stopped

networks:
  it-service-network:
    driver: bridge

volumes:
  frontend-node-modules:
  bot-node-modules:
  bot-uploads: