version: '3.8'

services:
  frontend:
    container_name: ifconfig-frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/static-frontend/.env:/app/.env
    networks:
      - it-service-network
    restart: unless-stopped

  bot:
    container_name: ifconfig-bot
    build:
      context: ./packages/discord-bot
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./packages/discord-bot/.env:/app/.env
    networks:
      - it-service-network
    restart: unless-stopped

networks:
  it-service-network:
    driver: bridge