version: '3.8'

services:
  frontend:
    container_name: it-service-frontend
    build:
      context: ./packages/static-frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./packages/static-frontend/.env:/app/.env
    networks:
      - it-service-network
    restart: unless-stopped

  bot:
    container_name: it-service-bot
    build:
      context: ./packages/discord-bot
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./packages/discord-bot/.env:/app/.env
    networks:
      - it-service-network
    restart: unless-stopped

networks:
  it-service-network:
    driver: bridge